### ISSUE TITLE
Robot Importer cannot load urdf file with .fbx meshes

### ISSUE THREAD

**Issue by hhaofan** [o3de/o3de-extras#121] opened 2023-01-13 16:43 UTC
**Bug description**
We need to use urdf with fbx format meshes to be able to apply materials within O3DE. But the 'robot importer' can not successfully import [urdf](https://github.com/hhaofan/urdf_fbx_minimum/blob/main/iiwa1_fbx.urdf) when it includes a [.fbx](https://github.com/hhaofan/urdf_fbx_minimum) mesh type instead of a [.stl](https://github.com/hhaofan/urdf_fbx_minimum), saying no CRC found.

**To Reproduce**

- Go to 'Robot Importer' and import the iiwa1_fbx.urdf file which uses EE_arm.fbx meshes (Files are included in the attachement)

- See error. And if we create the prefab regardlessly, we can see no meshes for the create entity

![image](https://user-images.githubusercontent.com/73705413/212371724-50929a05-bb2f-477d-aa32-989ef7b0bbae.png)

**Expected behavior**
Mesh properly imported in project without error reported, given that the format is supposed to be supported according to the code shared at:
https://github.com/RobotecAI/o3de-ros2-gem/blob/development/Code/Source/RobotImporter/Utils/SourceAssetsStorage.cpp#L35
**Screenshots / videos**

**Test environment**
 - OS: Ubuntu 20.04
 - ROS: Galactic

**Additional context**
- When I try to use Blender to view the EE_arm.fbx mesh, it works well, proving the fbx file has no problem.

![image](https://user-images.githubusercontent.com/73705413/212371814-e3a09e45-b39d-4674-8eaf-a46991ce11a5.png)
 
- If I add a single entity in the editor and include a mesh component using the same .fbx mesh file previously used for the URDF, then it looks how it is supposed to in the scene. This proves that **O3DE** properly supports the conditions for the .fbx mesh file we are using.

![image](https://user-images.githubusercontent.com/73705413/212372273-a5384643-d31e-4d7d-9cb4-0d37cd0eadd8.png)

- When I try to import the urdf file with robot importer including the same fbx mesh file, it doesn't import successfully, giving the following error:

![image](https://user-images.githubusercontent.com/73705413/212371875-9c3b40c3-e17f-40e9-ac3d-1c67bfe704e5.png)

- With the same urdf file, same mesh but converted to the [EE_arm.stl](https://github.com/hhaofan/urdf_fbx_minimum) format instead (files included in the attachement), the robot importer loads the mesh successfully, proving the urdf file and the mesh data are not the source of the problem.

![image](https://user-images.githubusercontent.com/73705413/212371900-0920c2e1-f50e-4708-990a-8ded7d098f7f.png)

**Comment by hultonha** [comment] 2023-02-09 09:18
Update: Discussed in sig-simulation issue, it is likely there is a version mismatch or some issue with the environment setup that is causing this problem. @michalpelka has volunteered to follow-up if @hhaofan you are still experiencing this issue. If you could share any more details about your setup that would be super helpful! Thanks!

**Comment by michalpelka** [comment] 2023-02-09 12:58
Hello @hhaofan ,
let me answer questions first:

- [error_log2(o3de-physics-test-scene Project)](https://github.com/hhaofan/urdf_fbx_minimum/blob/main/CMakeProjectBuildError_physics_test_scene.log).  - it is caused by using `release` version of engine instead of `develop` please pull the lastest [development](https://github.com/o3de/o3de/tree/development) here. You version does not have modification to PhysX gem.
- [error_log1(Ros2WarehouseDemo Project)](https://github.com/hhaofan/urdf_fbx_minimum/blob/main/CMakeProjectBuildError_Warehouse.log) - here you experiencing a bug that was fixed few days ago #122.
- The [Ros2WarehouseDemo Project](https://github.com/RobotecAI/Ros2WarehouseDemo) is no more. We moved all content as [Project template](https://github.com/o3de/o3de-extras/blob/development/Templates/Ros2ProjectTemplate/README.md)

I would recommend setup the project from scratch using a project [template](https://github.com/o3de/o3de-extras/blob/development/Templates/Ros2ProjectTemplate/README.md) with the newest version of o3de:development and o3de-extras:development.

**Comment by hhaofan** [comment] 2023-02-10 18:20
Hello @michalpelka ,
Thanks for the detailed answer and suggestions. However, I encountered with some errors again when building the template project following the [template Readme](https://github.com/o3de/o3de-extras/blob/development/Templates/Ros2ProjectTemplate/README.md).

- I switched to the development branch and the latest version both for o3de (0184d3df92ea39402d2a714ecca892032335c154) and o3de-extra (f1d8afed71cc31c7f538c548e2d5de4104b7501b). And when I followed the template instructions to build the [WarehouseSample](https://github.com/o3de/o3de-extras/tree/development/Gems/WarehouseSample) and the [RosRobotSample](https://github.com/o3de/o3de-extras/tree/development/Gems/RosRobotSample). I get errors listed below. Do you have some ideas on that?
    - [error_log_WarehouseSample](https://github.com/hhaofan/urdf_fbx_minimum/blob/main/CMakeProjectBuildError_Warehousesample.log)
    - [error_log_RosRobotSample](https://github.com/hhaofan/urdf_fbx_minimum/blob/main/CMakeError_RosRobotSample.log) 
 - Also, when I look at the o3de branch I am using. It still seems to be some errors of the [o3de version](https://jenkins.build.o3de.org/blue/organizations/jenkins/O3DE/detail/development/3917/pipeline)(where I found in the [commit check](https://github.com/o3de/o3de/commits/development) for the o3de branch). So could you suggest some stable version of o3de that you are using when building projects? 
 - As for the template you provided, I noticed that now both the WarehouseSample and the RosRobotSample become the Gem for o3de. And the project building sequence becomes: register these "project-like" Gems->enable these Gems, instead of the normal steps (register the ros2-gem->register the project). But when building the projects like [o3de-physics-test-scene](https://github.com/o3de/o3de-physics-test-scene), should we also regard them as the gems or should we build them following similar the building instructions in [RosConDemo](https://github.com/o3de/ROSConDemo#building-this-project)?

Thanks in advance for your assistance!

**Comment by hhaofan** [comment] 2023-02-23 13:47
Hi @michalpelka,

Thank you for the help! After shifting the o3de-extra commit to 964526be84c7d89184995fa60b72338a3e714090, I have successfully run all of the WarehouseSample, RosRobotSample and the [o3de-physics-test-scene](https://github.com/o3de/o3de-physics-test-scene) based on your instructions. What's more, the [fbx mesh loading problem in URDF Importer](https://github.com/o3de/o3de-extras/issues/121#issue-1574013022) described beforehand is finally solved with the o3de-extra commit (964526be84c7d89184995fa60b72338a3e714090) and o3de commit(f829a0687ae271966ad063c1278df9928f2c7b2b), and with different names between each mesh files. I can eventually successfully load all of the .fbx, .stl, and .dae meshes :) Thanks a lot for the help all the way!

**Comment by michalpelka** [comment] 2023-02-24 15:16
Happy to hear @hhaofan, closing the issue.

**Closed by michalpelka** 2023-02-24 15:16 UTC
Labels: kind/bug, triage/accepted, priority/major, sig/simulation, feature/robotics
