### ISSUE TITLE
FollowingCamera component shakes a lot

### ISSUE THREAD

**Issue by Fireronin** [o3de/o3de-extras#702] opened 2024-06-05 13:44 UTC
**Describe the bug**
Following Camera creates lot's of shaking when the object stops, and starts moving, this happens when this behavior via imgui. 

**Steps to reproduce**
1. Create object that move with random jumpy motion
2. Add following camera with with smoothing length set to 10
3. In game start and stop this object with imgui

**Expected behavior**
Camera moves smoothy object moves in jagged motion.

**Actual behavior**
At the start everything is fine, after stopping and starting objects movement camera jumps a loot creating blurry image.

**Commit ID from [o3de/o3de](https://github.com/o3de/o3de) and [o3de/o3de-extras](https://github.com/o3de/o3de-extras) repositories**
O3DE = tag: 2023.3
o3de-extras = commit id:  8297322

**Desktop/Device (please complete the following information):**
 - Device: PC
 - OS: Linux Ubuntu 22.04

 - CPU i7-14700K
 - GPU  NVidia RTX 4070Ti super
 - Memory 64GB

**Additional context**
In my experiments this this issue wasn't present when object moved few times per second, but was quite visible when movement happened around 15 times per second.

**Comment by michalpelka** [comment] 2024-06-21 09:03
Could you provide a video or level to reproduce? Without that, we cannot produce it.
The algorithm for camera smoothing is a simple low-pass filter implemented on quaternions and vectors. Please provide me exact use-case.
Note that what you expect in `Expected behavior` cannot be done in my opinion with this component. If you shake an object randomly (white noise assumption), you introduce a noise energy in a whole frequency spectrum. 
The smoothing is done via a low-pass filter. Those filters have some amount of damping of high-frequency signals, but cannot magically find what is a signal and what is a noise. It is based on the assumption that noise is rather high frequency (e.g. robot that drives on uneven terrain).
I can two possibilities to solve this problem:
- using the following camera against a "ghost" entity that is free of noise. Movement will be super-smooth.
- introduce advanced filtering technique (project-specific) - implement SE(3) based Extended Kalman filter and replace low-pass filter. Since EKF has a little more "magic" due to a motion model, it will still let some noise energy pass through. If you would like to implement that I can recommend you :
 - a paper on dealing with rotation in EKF: https://arxiv.org/pdf/1812.01537
 - an excellent interactive book on signal processing https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python

I also cannot understand what you mean by blury image. Currently, we have no motion blur implemented, and Atom does not simulate exposure-time blurring.
I think that issue is not valid here, but to be 100% percent sure, please provide me a with repoduction.

**Comment by michalpelka** [comment] 2024-06-21 09:07
I suggest a reproduction as some lua script that will shake an object similar to what you observe in your project

**Comment by jhanca-robotecai** [comment] 2024-07-05 08:22
I am closing this issue based on the missing reproduction. Please reopen when ready.

**Closed by jhanca-robotecai** 2024-07-05 08:22 UTC
Labels: kind/bug, triage/needs-inforamtion, needs-triage, sig/simulation
