### ISSUE TITLE
Missing R2PTSampleComponent in RosRobotTemplate demo level

### ISSUE THREAD

**Issue by yangfengzzz** [o3de/o3de-extras#780] opened 2024-10-30 04:13 UTC
WHen I Load demo level， It shows
```
Unable to resolve provided type: R2PTSampleComponent.
    Reason: The operation has halted during a retrieve info operation for '/Entities/Entity_[541237100205]/Components/Component_[2318932367744128274]/m_template' because information was missing.
```

**Comment by jhanca-robotecai** [comment] 2024-10-30 12:09
Thank you for raising the issue. Could you please confirm which version of o3de and which version of the template (o3de-extras) you use? 

I remember this problem: it was fixed in https://github.com/o3de/o3de-extras/pull/723 
I cannot reproduce it using the last release (2409.0).

**Comment by yangfengzzz** [comment] 2024-10-31 03:52
I use 2409 and clone this repo with hashtag 830e7262

**Comment by spham-amzn** [comment] 2024-11-08 19:23
I am able to reproduce this with 2409.1 through project manager
![image](https://github.com/user-attachments/assets/cd47bf4d-d12d-468a-ace2-826342dac95f)

**Comment by spham-amzn** [comment] 2024-11-08 22:04
It looks like the root cause is from this [commit](https://github.com/o3de/o3de-extras/commit/efe2c1dae85b6575473885ebb026760ba9aa9571#diff-3c9d8e301f39004378bf425fb3a894ae6bb5f871db207e8f78f612096167c0c8L354). This [line](https://github.com/o3de/o3de-extras/blob/110312c7acf4dc1c37038ac8f8f7584315f688f0/Templates/Ros2ProjectTemplate/Template/Levels/DemoLevel/DemoLevel.prefab#L271) `${SanitizedCppName}SampleComponent"` was replaced in the DemoLevel.prefab template with `R2PTSampleComponent`, probably from an instantiated template. This needs to be reverted to 
```
 "$type": "${SanitizedCppName}SampleComponent",
```
instead

**Closed** 2024-11-19 11:48 UTC
Labels: kind/bug, needs-triage, sig/simulation
